<?php

namespace App\Modules\Asaas\DTO\Webhook;

class AsaasCreateOrUpdateWebhookDataDTO
{
    public function __construct(
        public readonly string $event_id,
        public readonly string $event,
        public readonly string $change_date,
        public readonly string $object,
        public readonly string $payment_id,
        public readonly string $payment_date_created,
        public readonly string $customer_id,
        public readonly ?string $checkout_session,
        public readonly ?string $payment_link,
        public readonly float $value,
        public readonly float $net_value,
        public readonly ?float $original_value,
        public readonly ?float $interest_value,
        public readonly ?string $description,
        public readonly string $billing_type,
        public readonly ?string $confirmed_date,
        public readonly ?string $pix_transaction,
        public readonly string $status,
        public readonly string $due_date,
        public readonly string $original_due_date,
        public readonly ?string $settlement_date,
        public readonly ?string $client_payment_date,
        public readonly ?int $installment_number,
        public readonly string $invoice_url,
        public readonly int $invoice_number,
        public readonly ?string $external_reference,
        public readonly bool $deleted,
        public readonly bool $anticipated,
        public readonly bool $anticipable,
        public readonly ?string $credit_date,
        public readonly ?string $estimated_credit_date,
        public readonly ?string $transaction_receipt_url,
        public readonly ?string $nosso_numero,
        public readonly ?string $bank_slip_url,
        public readonly ?string $last_invoice_viewed_date,
        public readonly ?string $last_bank_slip_viewed_date,
        public readonly float $discount_value,
        public readonly ?string $discount_limit_date,
        public readonly int $due_date_limit_days,
        public readonly string $discount_type,
        public readonly float $fine_value,
        public readonly string $fine_type,
        public readonly string $interest_type,
        public readonly bool $postal_service,
        public readonly ?string $escrow_id,
        public readonly ?string $escrow_status,
        public readonly ?string $escrow_expiration_date,
        public readonly ?string $escrow_finish_date,
        public readonly ?string $escrow_finish_reason,
        public readonly ?string $refund_date_created,
        public readonly ?string $refund_status,
        public readonly ?float $refund_value,
        public readonly ?string $refund_end_to_end_identifier,
        public readonly ?string $refund_description,
        public readonly ?string $refund_effective_date,
        public readonly ?string $refund_transaction_receipt_url,
        public readonly int $user_id,
        public readonly ?string $pix_qr_code_id,
        public readonly string $project_name,
    ) {}

    public static function fromRequest($data): self
    {
        $parts = explode('|', $data['payment']['externalReference']);
        $projectName = $parts[0];
        $userPart = $parts[1];
        $userId = str_replace('user_', '', $userPart);

        return new self(
            event_id: $data['id'],
            event: $data['event'],
            change_date: $data['dateCreated'],
            object: $data['payment']['object'],
            payment_id: $data['payment']['id'],
            payment_date_created: $data['payment']['dateCreated'],
            customer_id: $data['payment']['customer'],
            checkout_session: ['payment']['checkoutSession'] ?? null,
            payment_link: $data['payment']['paymentLink'] ?? null,
            value: $data['payment']['value'],
            net_value: $data['payment']['netValue'],
            original_value: $data['payment']['originalValue'] ?? null,
            description: $data['payment']['description'] ?? null,
            billing_type: $data['payment']['billingType'],
            confirmed_date: $data['payment']['confirmedDate'] ?? null,
            pix_transaction: $data['payment']['pixTransaction'] ?? null,
            status: $data['payment']['status'],
            due_date: $data['payment']['dueDate'],
            original_due_date: $data['payment']['originalDueDate'],
            settlement_date: $data['payment']['paymentDate'] ?? null,
            client_payment_date: $data['payment']['clientPaymentDate'] ?? null,
            installment_number: $data['payment']['installmentNumber'] ?? null,
            invoice_url: $data['payment']['invoiceUrl'],
            invoice_number: $data['payment']['invoiceNumber'] ?? null,
            external_reference: $data['payment']['externalReference'],
            deleted: $data['payment']['deleted'],
            anticipated: $data['payment']['anticipated'],
            anticipable: $data['payment']['anticipable'],
            credit_date: $data['payment']['creditDate'] ?? null,
            estimated_credit_date: $data['payment']['estimatedCreditDate'] ?? null,
            transaction_receipt_url: $data['payment']['transactionReceiptUrl'] ?? null,
            nosso_numero: $data['payment']['nossoNumero'] ?? null,
            bank_slip_url: $data['payment']['bankSlipUrl'] ?? null,
            last_invoice_viewed_date: $data['payment']['lastInvoiceViewedDate'] ?? null,
            last_bank_slip_viewed_date: $data['payment']['lastBankSlipViewedDate'] ?? null,
            discount_value: $data['payment']['discount']['value'] ?? 0,
            discount_limit_date: $data['payment']['discount']['limitDate'] ?? null,
            due_date_limit_days: $data['payment']['discount']['dueDateLimitDays'] ?? null,
            discount_type: $data['payment']['discount']['type'] ?? null,
            fine_value: $data['payment']['fine']['value'] ?? null,
            fine_type: $data['payment']['fine']['type'] ?? null,
            interest_value: $data['payment']['interest']['value'] ?? null,
            interest_type: $data['payment']['interest']['type'] ?? null,
            postal_service: $data['payment']['postalService'] ?? null,
            escrow_id: $data['payment']['escrow']['id'] ?? null,
            escrow_status: $data['payment']['escrow']['status'] ?? null,
            escrow_expiration_date: $data['payment']['escrow']['expirationDate'] ?? null,
            escrow_finish_date: $data['payment']['escrow']['finishDate'] ?? null,
            escrow_finish_reason: $data['payment']['escrow']['finishReason'] ?? null,
            refund_date_created: $data['payment']['refunds']['dateCreated'] ?? null,
            refund_status: $data['payment']['refunds']['status'] ?? null,
            refund_value: $data['payment']['refunds']['value'] ?? null,
            refund_end_to_end_identifier: $data['payment']['refunds']['endToEndIdentifier'] ?? null,
            refund_description: $data['payment']['refunds']['description'] ?? null,
            refund_effective_date: $data['payment']['refunds']['effectiveDate'] ?? null,
            refund_transaction_receipt_url: $data['payment']['refunds']['transactionReceiptUrl'] ?? null,
            user_id : (int) $userId,
            pix_qr_code_id: $data['payment']['pixQrCodeId'] ?? null,
            project_name: $projectName,
        );
    }

    public function toArray(): array
    {
        return [
            'event_id' => $this->event_id,
            'event' => $this->event,
            'change_date' => $this->change_date,
            'object' => $this->object,
            'payment_id' => $this->payment_id,
            'payment_date_created' => $this->payment_date_created,
            'customer_id' => $this->customer_id,
            'checkout_session' => $this->checkout_session,
            'payment_link' => $this->payment_link,
            'value' => $this->value,
            'net_value' => $this->net_value,
            'original_value' => $this->original_value,
            'interest_value' => $this->interest_value,
            'description' => $this->description,
            'billing_type' => $this->billing_type,
            'confirmed_date' => $this->confirmed_date,
            'pix_transaction' => $this->pix_transaction,
            'status' => $this->status,
            'due_date' => $this->due_date,
            'original_due_date' => $this->original_due_date,
            'settlement_date' => $this->settlement_date,
            'client_payment_date' => $this->client_payment_date,
            'installment_number' => $this->installment_number,
            'invoice_url' => $this->invoice_url,
            'invoice_number' => $this->invoice_number,
            'external_reference' => $this->external_reference,
            'deleted' => $this->deleted,
            'anticipated' => $this->anticipated,
            'anticipable' => $this->anticipable,
            'credit_date' => $this->credit_date,
            'estimated_credit_date' => $this->estimated_credit_date,
            'transaction_receipt_url' => $this->transaction_receipt_url,
            'nosso_numero' => $this->nosso_numero,
            'bank_slip_url' => $this->bank_slip_url,
            'last_invoice_viewed_date' => $this->last_invoice_viewed_date,
            'last_bank_slip_viewed_date' => $this->last_bank_slip_viewed_date,
            'discount_value' => $this->discount_value,
            'discount_limit_date' => $this->discount_limit_date,
            'due_date_limit_days' => $this->due_date_limit_days,
            'discount_type' => $this->discount_type,
            'fine_value' => $this->fine_value,
            'fine_type' => $this->fine_type,
            'interest_type' => $this->interest_type,
            'postal_service' => $this->postal_service,
            'escrow_id' => $this->escrow_id,
            'escrow_status' => $this->escrow_status,
            'escrow_expiration_date' => $this->escrow_expiration_date,
            'escrow_finish_date' => $this->escrow_finish_date,
            'escrow_finish_reason' => $this->escrow_finish_reason,
            'refund_date_created' => $this->refund_date_created,
            'refund_status' => $this->refund_status,
            'refund_value' => $this->refund_value,
            'refund_end_to_end_identifier' => $this->refund_end_to_end_identifier,
            'refund_description' => $this->refund_description,
            'refund_effective_date' => $this->refund_effective_date,
            'refund_transaction_receipt_url' => $this->refund_transaction_receipt_url,
            'user_id' => $this->user_id,
            'pix_qr_code_id' => $this->pix_qr_code_id,
            'project_name' => $this->project_name
        ];
    }
}
