<?php

namespace App\Modules\Asaas\DTO\Webhook;

class AsaasCreateOrUpdateWebhookDataDTO
{
    public function __construct(
        public readonly string $event_id,
        public readonly string $event,
        public readonly string $change_date,
        public readonly string $object,
        public readonly string $payment_id,
        public readonly string $payment_date_created,
        public readonly string $customer_id,
        public readonly ?string $checkout_session,
        public readonly ?string $payment_link,
        public readonly float $value,
        public readonly float $net_value,
        public readonly ?float $original_value,
        public readonly ?float $interest_value,
        public readonly ?string $description,
        public readonly string $billing_type,
        public readonly ?string $confirmed_date,
        public readonly ?string $pix_transaction,
        public readonly string $status,
        public readonly string $due_date,
        public readonly string $original_due_date,
        public readonly ?string $settlement_date,
        public readonly ?string $client_payment_date,
        public readonly ?int $installment_number,
        public readonly string $invoice_url,
        public readonly int $invoice_number,
        public readonly ?string $external_reference,
        public readonly bool $deleted,
        public readonly bool $anticipated,
        public readonly bool $anticipable,
        public readonly ?string $credit_date,
        public readonly ?string $estimated_credit_date,
        public readonly ?string $transaction_receipt_url,
        public readonly ?string $nosso_numero,
        public readonly ?string $bank_slip_url,
        public readonly ?string $last_invoice_viewed_date,
        public readonly ?string $last_bank_slip_viewed_date,
        public readonly float $discount_value,
        public readonly ?string $discount_limit_date,
        public readonly int $due_date_limit_days,
        public readonly string $discount_type,
        public readonly float $fine_value,
        public readonly string $fine_type,
        public readonly string $interest_type,
        public readonly bool $postal_service,
        public readonly ?string $escrow_id,
        public readonly ?string $escrow_status,
        public readonly ?string $escrow_expiration_date,
        public readonly ?string $escrow_finish_date,
        public readonly ?string $escrow_finish_reason,
        public readonly ?string $refund_date_created,
        public readonly ?string $refund_status,
        public readonly ?float $refund_value,
        public readonly ?string $refund_end_to_end_identifier,
        public readonly ?string $refund_description,
        public readonly ?string $refund_effective_date,
        public readonly ?string $refund_transaction_receipt_url,
        public readonly int $user_id,
        public readonly ?string $pix_qr_code_id,
    ) {}

    public static function fromRequest($data): self
    {
        return new self(
            event_id: $data['event_id'],
            event: $data['event'],
            change_date: $data['change_date'],
            object: $data['object'],
            payment_id: $data['payment_id'],
            payment_date_created: $data['payment_date_created'],
            customer_id: $data['customer_id'],
            checkout_session: $data['checkout_session'] ?? null,
            payment_link: $data['payment_link'] ?? null,
            value: $data['value'],
            net_value: $data['net_value'],
            original_value: $data['original_value'] ?? null,
            description: $data['description'] ?? null,
            billing_type: $data['billing_type'],
            confirmed_date: $data['confirmed_date'] ?? null,
            pix_transaction: $data['pix_transaction'] ?? null,
            status: $data['status'],
            due_date: $data['due_date'],
            original_due_date: $data['original_due_date'],
            settlement_date: $data['settlement_date'] ?? null,
            client_payment_date: $data['client_payment_date'] ?? null,
            installment_number: $data['installment_number'] ?? null,
            invoice_url: $data['invoice_url'],
            invoice_number: $data['invoice_number'] ?? null,
            external_reference: $data['external_reference'] ?? null,
            deleted: $data['deleted'],
            anticipated: $data['anticipated'],
            anticipable: $data['anticipable'],
            credit_date: $data['credit_date'] ?? null,
            estimated_credit_date: $data['estimated_credit_date'] ?? null,
            transaction_receipt_url: $data['transaction_receipt_url'] ?? null,
            nosso_numero: $data['nosso_numero'] ?? null,
            bank_slip_url: $data['bank_slip_url'] ?? null,
            last_invoice_viewed_date: $data['last_invoice_viewed_date'] ?? null,
            last_bank_slip_viewed_date: $data['last_bank_slip_viewed_date'] ?? null,
            discount_value: $data['discount_value'] ?? 0,
            discount_limit_date: $data['discount_limit_date'] ?? null,
            due_date_limit_days: $data['due_date_limit_days'],
            discount_type: $data['discount_type'],
            fine_value: $data['fine_value'],
            fine_type: $data['fine_type'],
            interest_value: $data['interest_value'],
            interest_type: $data['interest_type'],
            postal_service: $data['postal_service'],
            escrow_id: $data['escrow_id'] ?? null,
            escrow_status: $data['escrow_status'] ?? null,
            escrow_expiration_date: $data['escrow_expiration_date'] ?? null,
            escrow_finish_date: $data['escrow_finish_date'] ?? null,
            escrow_finish_reason: $data['escrow_finish_reason'] ?? null,
            refund_date_created: $data['refund_date_created'] ?? null,
            refund_status: $data['refund_status'] ?? null,
            refund_value: $data['refund_value'] ?? null,
            refund_end_to_end_identifier: $data['refund_end_to_end_identifier'] ?? null,
            refund_description: $data['refund_description'] ?? null,
            refund_effective_date: $data['refund_effective_date'] ?? null,
            refund_transaction_receipt_url: $data['refund_transaction_receipt_url'] ?? null,
            user_id: $data['user_id'],
            pix_qr_code_id: $data['pix_qr_code_id'] ?? null
        );
    }

    public function toArray(): array
    {
        return [
            'event_id' => $this->event_id,
            'event' => $this->event,
            'change_date' => $this->change_date,
            'object' => $this->object,
            'payment_id' => $this->payment_id,
            'payment_date_created' => $this->payment_date_created,
            'customer_id' => $this->customer_id,
            'checkout_session' => $this->checkout_session,
            'payment_link' => $this->payment_link,
            'value' => $this->value,
            'net_value' => $this->net_value,
            'original_value' => $this->original_value,
            'interest_value' => $this->interest_value,
            'description' => $this->description,
            'billing_type' => $this->billing_type,
            'confirmed_date' => $this->confirmed_date,
            'pix_transaction' => $this->pix_transaction,
            'status' => $this->status,
            'due_date' => $this->due_date,
            'original_due_date' => $this->original_due_date,
            'settlement_date' => $this->settlement_date,
            'client_payment_date' => $this->client_payment_date,
            'installment_number' => $this->installment_number,
            'invoice_url' => $this->invoice_url,
            'invoice_number' => $this->invoice_number,
            'external_reference' => $this->external_reference,
            'deleted' => $this->deleted,
            'anticipated' => $this->anticipated,
            'anticipable' => $this->anticipable,
            'credit_date' => $this->credit_date,
            'estimated_credit_date' => $this->estimated_credit_date,
            'transaction_receipt_url' => $this->transaction_receipt_url,
            'nosso_numero' => $this->nosso_numero,
            'bank_slip_url' => $this->bank_slip_url,
            'last_invoice_viewed_date' => $this->last_invoice_viewed_date,
            'last_bank_slip_viewed_date' => $this->last_bank_slip_viewed_date,
            'discount_value' => $this->discount_value,
            'discount_limit_date' => $this->discount_limit_date,
            'due_date_limit_days' => $this->due_date_limit_days,
            'discount_type' => $this->discount_type,
            'fine_value' => $this->fine_value,
            'fine_type' => $this->fine_type,
            'interest_type' => $this->interest_type,
            'postal_service' => $this->postal_service,
            'escrow_id' => $this->escrow_id,
            'escrow_status' => $this->escrow_status,
            'escrow_expiration_date' => $this->escrow_expiration_date,
            'escrow_finish_date' => $this->escrow_finish_date,
            'escrow_finish_reason' => $this->escrow_finish_reason,
            'refund_date_created' => $this->refund_date_created,
            'refund_status' => $this->refund_status,
            'refund_value' => $this->refund_value,
            'refund_end_to_end_identifier' => $this->refund_end_to_end_identifier,
            'refund_description' => $this->refund_description,
            'refund_effective_date' => $this->refund_effective_date,
            'refund_transaction_receipt_url' => $this->refund_transaction_receipt_url,
            'user_id' => $this->user_id,
            'pix_qr_code_id' => $this->pix_qr_code_id,
        ];
    }
}
